export const sexe = [
    { value: 'Mâle',text: 'Mâle'},
    { value: 'Femelle',text: 'Femelle'},
  ];

export const age = [
    {value: 1,text: 1},
    {value: 2,text: 2},
    {value: 3,text: 3},
    {value: 4,text: 4},
    {value: 5,text: 5},
    {value: 6,text: 6},
    {value: 7,text: 7},
    {value: 8,text: 8},
    {value: 9,text: 9},
    {value: 10,text: 10},
    {value: 11,text: 11},
    {value: 12,text: 12},
    {value: 13,text: 13},
    {value: 14,text: 14},
    {value: 15,text: 15},
    {value: 16,text: 16},
    {value: 17,text: 17},
    {value: 18,text: 18},
    {value: 19,text: 19},
    {value: 20,text: 20},
    {value: 21,text: 21},
    {value: 22,text: 22},
    {value: 23,text: 23},
  ];

export const taille = [
    {value: 'petit', text: "Petit"},
    {value: 'moyen',text: "Moyen"},
    {value: 'grand',text: "Grand"},
  ]

export const breeds = [
    "Affenpinscher",
    "Airedale Terrier",
    "Akita américain",
    "Akita inu",
    "Alaskan Klee Kai",
    "american bully standard",
    "American Bully",
    "American staffordshire Terrier",
    "Ariégeois",
    "Azawakh",
    "Barbet",
    "Barbu tchèque",
    "Barzoï",
    "Basenji",
    "Basset artésien normand",
    "Basset de Westphalie",
    "Basset des Alpes",
    "Basset fauve de Bretagne",
    "Basset hound",
    "Beagle",
    "Beagle-harrier",
    "Bearded collie",
    "Beauceron",
    "Bedlington terrier",
    "Berger Allemand",
    "Berger Australien",
    "Mini berger Australien",
    "Berger Australien Miniature",
    "berger belge Groenendael",
    "berger belge laekenois",
    "Berger belge Malinois",
    "berger belge tervueren gris",
    "Berger Belge Tervueren",
    "Berger blanc suisse",
    "Berger catalan",
    "Berger Créole",
    "berger d'anatolie",
    "Berger d’Anatolie",
    "Berger d’Asie centrale",
    "Berger d’Islande",
    "Berger de Bergame",
    "Berger de Brie",
    "Berger de l’Atlas",
    "Berger de Marenne et des Abruzzes",
    "Berger de Russie",
    "berger des pyrénées",
    "Berger des Shetland ou Sheltie",
    "Berger du Caucase",
    "Berger du Karst",
    "berger finnois de Laponie",
    "berger hollandais",
    "Berger Picard",
    "Berger polonais de plaine",
    "Berger polonais de Podhale",
    "Berger portugais",
    "Berger yougoslave",
    "Bichon à poil frisé",
    "bichon bolonais",
    "Bichon bolonais",
    "Bichon havanais",
    "Bichon maltais",
    "Billy",
    "Black and tan coonhound",
    "Bobtail",
    "boerbull",
    "Border Collie",
    "border terrier",
    "Border terrier",
    "Boston Terrier",
    "bouledogue américain",
    "Bouledogue français",
    "Bouvier Australien",
    "la race du Bouvier Bernois",
    "Bouvier bernois",
    "Bouvier d’Appenzell",
    "Bouvier de l’Entlebuch",
    "Bouvier des Ardennes",
    "Bouvier des Flandres",
    "Boxer",
    "Brachet allemand",
    "Brachet autrichien",
    "Brachet de Styrie à poil dur",
    "Brachet polonais",
    "Brachet tyrolien",
    "braque allemand à poil court",
    "Braque d’Auvergne",
    "Braque de Burgos",
    "Braque de l’Ariège",
    "braque de weimar",
    "Braque de Weimar",
    "Braque du Bourbonnais",
    "Braque français",
    "Braque hongrois à poil court",
    "Braque hongrois à poil dur",
    "Braque italien",
    "Braque Saint-Germain",
    "Braque slovaque à poil dur",
    "Briquet griffon vendéen",
    "Broholmer",
    "Buhund norvégien",
    "Bull terrier",
    "Bulldog anglais",
    "Bullmastiff",
    "Cairn terrier",
    "Cane corso",
    "Caniche",
    "caniche moyen",
    "caniche nain",
    "Caniche Royal",
    "Caniche Toy",
    "Cao fila de São Miguel",
    "Carlin ou Pug",
    "Cavalier King Charles",
    "Chesapeake Bay Retriever",
    "Chien chinois à crête",
    "Chien courant bernois",
    "Chien courant de Bosnie à poil dur",
    "Chien courant de Halden",
    "Chien courant de Hygen",
    "Chien courant de Posavatz",
    "Chien courant de Schwyz",
    "Chien courant de Transylvanie",
    "Chien courant d’Istrie à poil dur",
    "Chien courant d’Istrie à poil ras",
    "Chien courant espagnol",
    "Chien courant finlandais",
    "Chien courant grec",
    "Chien courant italien à poil dur",
    "Chien courant italien à poil ras",
    "Chien courant serbe",
    "Chien courant slovaque",
    "Chien courant suisse",
    "Chien courant yougoslave de montagne",
    "Chien courant yougoslave tricolore",
    "Chien d’arrêt allemand à poil long",
    "Chien d’arrêt portugais",
    "Chien d’Artois",
    "Chien d’eau américain",
    "Chien d’eau espagnol",
    "Chien d’eau frison",
    "Chien d’eau irlandais",
    "Chien d’eau portugais",
    "Chien d’eau romagnol",
    "Chien d’élan norvégien",
    "Chien de berger de Croatie",
    "Chien de berger de Majorque",
    "Chien de Canaan",
    "Chien de Castro Laboreiro",
    "Chien de montagne des Pyrénées",
    "Chien de montagne portugais",
    "Chien de Saint-Hubert",
    "Chien de Taïwan",
    "Chien du Groenland",
    "Chien du pharaon",
    "Chien d’élan suédois",
    "Chien d’ours de Carélie",
    "Chien d’Oysel",
    "Chien finnois de Laponie",
    "Chien norvégien de Macareux",
    "Chien nu du Pérou",
    "Chien nu mexicain",
    "Chien rouge de Bavière",
    "Chien rouge de Hanovre",
    "Chien suédois de Laponie",
    "Chien thaïlandais",
    "Chien-loup de Saarloos",
    "Chien-loup Tchèque",
    "beau chihuahua",
    "Chihuahua",
    "Chihuahua à poil long",
    "Chow-chow",
    "Cirneco de l’Etna",
    "Clumber Spaniel",
    "cocker américain",
    "Cocker anglais",
    "Colley à poil court",
    "Colley à poil long – Collie rough",
    "Coton de Tuléar",
    "Dalmatien",
    "Dandie Dinmont Terrier",
    "dobermann",
    "Dogo Canario",
    "dogue-allemand",
    "Dogue allemand",
    "Dogue argentin",
    "dogue de bordeaux",
    "Dogue de Bordeaux",
    "Dogue de Majorque",
    "Dogue du Tibet",
    "Drever",
    "Dunker",
    "Epagneul à perdrix de Drente",
    "Epagneul bleu de Picardie",
    "Epagneul breton",
    "Epagneul de Pont-Audemer",
    "Epagneul français",
    "Epagneul japonais",
    "Epagneul nain continental",
    "Epagneul picard",
    "Epagneul tibétain",
    "Eurasier",
    "Field Spaniel",
    "Fila Brasileiro",
    "Flat-Coated Retriever",
    "fox terrier race de chien",
    "Fox Terrier",
    "Foxhound américain",
    "Foxhound anglais",
    "Français blanc et noir",
    "Français tricolore",
    "gascon saintongeois",
    "Golden Retriever",
    "Goldendoodle",
    "Grand Anglo-Français blanc et noir",
    "Grand Anglo-Français blanc et orange",
    "Grand Anglo-Français tricolore",
    "Grand Basset Griffon vendéen",
    "Grand bleu de Gascogne",
    "Grand bouvier suisse",
    "Grand épagneul de Münster",
    "Grand Griffon vendéen",
    "Greyhound",
    "Griffon belge",
    "Griffon bruxellois",
    "Griffon fauve de Bretagne",
    "Griffon Korthals",
    "Griffon nivernais",
    "Hamilton stövare",
    "Harrier",
    "Hokkaido Ken",
    "Hovawart",
    "race Husky Sibérien",
    "Husky sibérien",
    "Jack Russel",
    "Jagdterrier",
    "Jindo coréen",
    "Kai",
    "Kelpie australien",
    "Kerry Blue Terrier",
    "Kishu",
    "Komondor",
    "Kromfohrländer",
    "Kuvasz",
    "Labradoodle",
    "Labrador",
    "Laïka de Sibérie occidentale",
    "Laïka de Sibérie orientale",
    "Lakeland Terrier",
    "Landseer",
    "Léonberg",
    "Lévrier afghan",
    "Lévrier écossais",
    "Lévrier espagnol",
    "Lévrier hongrois",
    "Lévrier irlandais",
    "Lévrier polonais",
    "race lhassa apso",
    "Lhassa Apso",
    "Malamute de l’Alaska",
    "Manchester terrier",
    "Mastiff",
    "Mâtin de Naples",
    "Mâtin espagnol",
    "morkie",
    "Mudi",
    "Norfolk Terrier",
    "Norwich Terrier",
    "old english bulldog",
    "Otterhound",
    "Parson Russell Terrier",
    "Pékinois",
    "Petit Basset Griffon Vendéen",
    "Petit bleu de Gascogne",
    "Petit brabançon",
    "Petit chien courant suisse",
    "Petit chien lion",
    "Petit Lévrier italien",
    "Petit Münsterländer",
    "Pinscher",
    "Pinscher autrichien à poil court",
    "Pinscher nain",
    "Pitbull ou American pitbull terrier",
    "Podenco canario",
    "Podenco ibicenco",
    "Podenco portugais",
    "Pointer anglais",
    "Poitevin",
    "Pomsky",
    "Porcelaine",
    "Pudelpointer",
    "Puli",
    "Pumi",
    "Rafeiro do Alentejo",
    "ratier de prague",
    "Retriever de la Nouvelle-Écosse",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Russkiy Toy",
    "saint bernard",
    "Saluki",
    "Samoyède",
    "Schnauzer",
    "Schnauzer géant",
    "Schnauzer moyen",
    "schnauzer nain",
    "Scottish Terrier",
    "Setter anglais",
    "Setter Gordon",
    "setter irlandais",
    "Shar Pei",
    "Shiba Inu",
    "Shih Tzu",
    "Shikoku Ken",
    "Silky Terrier",
    "Skye Terrier",
    "Sloughi",
    "Slovensky cuvac",
    "Smous des Pays-Bas",
    "Spinone",
    "Spitz allemand",
    "Spitz de Norrbotten",
    "Spitz des Wisigoths",
    "Spitz Finlandais",
    "Spitz japonais",
    "Spitz nain",
    "Spitz-loup",
    "Springer anglais",
    "Stabyhoun",
    "Staffordshire Bull Terrier",
    "Sussex Spaniel",
    "Tamaskan",
    "teckel",
    "teckel à poil dur",
    "teckel à poil long",
    "Teckel à poil ras",
    "Le teckel nain",
    "Teckel Nain",
    "race terre neuve",
    "Terre-neuve",
    "Terrier Irlandais",
    "Terrier Irlandais à poil doux",
    "Terrier Irlandais Glen of Imaal",
    "Terrier japonais",
    "Terrier noir russe",
    "Terrier tibétain",
    "tosa",
    "Race Welsh Corgi",
    "Welsh Corgi",
    "Welsh Springer Spaniel",
    "Welsh Terrier",
    "westie",
    "Whippet",
    "Yorkshire terrier",
    ]

     let TabBreeds = []
    breeds.map((breed) => {
        let objBreed = {};
        objBreed.value = breed
        objBreed.text = breed
        TabBreeds.push(objBreed)
        return TabBreeds;
    })

    export default TabBreeds;